name: hello-world
on:
  push:
      branches:
        - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run : echo "Hello World!"
        
      - name: clone my repo
        uses: actions/checkout@v1
        
      - name: print current folder
        run : ls -la
