name: hello-world
on:
  push:
      branches:
        - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone my repo
        uses: actions/checkout@v1
        
      - name: print current folder
        run : ls -la
        
      - name: print make version
        run : make --version
        
      - name: hello
        run : make say-hello
